// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddExpense(arg1:domain.Expense):Promise<domain.Expense>;

export function CreateBackup(arg1:string):Promise<domain.Backup>;

export function CreateVehicle(arg1:domain.Vehicle):Promise<domain.Vehicle>;

export function Greet(arg1:string):Promise<string>;

export function ListBackups():Promise<Array<domain.Backup>>;

export function ListVehicleExpenses(arg1:number):Promise<Array<domain.Expense>>;

export function ListVehicles():Promise<Array<domain.Vehicle>>;
