// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExpense(arg1) {
  return window['go']['handler']['App']['AddExpense'](arg1);
}

export function CreateBackup(arg1) {
  return window['go']['handler']['App']['CreateBackup'](arg1);
}

export function CreateVehicle(arg1) {
  return window['go']['handler']['App']['CreateVehicle'](arg1);
}

export function Greet(arg1) {
  return window['go']['handler']['App']['Greet'](arg1);
}

export function ListBackups() {
  return window['go']['handler']['App']['ListBackups']();
}

export function ListVehicleExpenses(arg1) {
  return window['go']['handler']['App']['ListVehicleExpenses'](arg1);
}

export function ListVehicles() {
  return window['go']['handler']['App']['ListVehicles']();
}
